---
# Whether the nova_libvirt container is enabled.
enable_nova_libvirt_container: false

# Whether to remove the AppArmor libvirt profile on Ubuntu hosts.
apparmor_remove_libvirt_profile: "{{ enable_nova_libvirt_container | bool }}"
